### ISSUE TITLE
当 `pixelRatio` 不为 `1.0`，在iOS端图片高度是压缩的

### ISSUE THREAD

**Issue by LiWenHui96** [AoEiuV020/listview_screenshot#1]

**Comment by AoEiuV020** [comment]
其实这个pixelRatio我还没使用过，所以函数注释里没提到，
这部分代码来自另一个项目，[AWarmHug/widget_screenshot](https://github.com/AWarmHug/widget_screenshot)
如果能提供使用场景的话我或许可以抽空试试，

**Comment by LiWenHui96** [comment]
很感谢您的回复。另外在苹果的真机上无法使用，虚拟机可以运行。

**Comment by AoEiuV020** [comment]
@LiWenHui96 是说这个库还是apps/example这个示例？
代码里应该没什么影响ios真机的，不过我确实还没测苹果真机，没买苹果开发者账号有点坑，

**Comment by LiWenHui96** [comment]
没有使用实例，是我自己的代码内实现的，不过等晚些时候我看下案例的情况吧。

**Comment by LiWenHui96** [comment]
[screenshot](https://pub.dev/packages/screenshot)这个插件的弊端是截取不完全，但是咱们这个目前是高度不正确。

**Comment by AoEiuV020** [comment]
这里长截图的原理是翻一页截一页最后合并，如果高度有问题的话， 得知道怎么复现了我好好看看哪里的问题，
