### ISSUE TITLE
速度是个很大的问题

### ISSUE THREAD

**Issue by LiWenHui96** [AoEiuV020/listview_screenshot#2]
使用`Image`对于开发来说是个很好的插件，但是他太慢了。[image/102](https://github.com/brendan-duncan/image/issues/102) [image/538](https://github.com/brendan-duncan/image/issues/538)

**Comment by AoEiuV020** [comment]
这个确实，不过没有找到更好的全平台方案了，
目前是异步合并与转换，甭管多慢别卡主线程就行了，

**Comment by AoEiuV020** [comment]
其实也还好，刚试了一下最新示例web端，mac mini m2上chrome测试截图，测试最长的200 items，翻页截图花了4秒，合并转换png花了11秒，最终图片是17M，像素1920*26376， 
这速度其实等得起，毕竟长截图也不是什么需要大量重复的操作，

**Comment by LiWenHui96** [comment]
我也不确定是什么问题，在iOS上特别慢，可能是像素过大还是什么原因，今天下午能到十分钟。LiWeNHuI在 2024年5月7日，20:24，啊o额iu鱼 ***@***.***> 写道：﻿
其实也还好，刚试了一下最新示例web端，mac mini m2上chrome测试截图，测试最长的200 items，翻页截图花了4秒，合并转换png花了11秒，最终图片是17M，像素1920*26376，
这速度其实等得起，毕竟长截图也不是什么需要大量重复的操作，

**Comment by LiWenHui96** [comment]
> 其实也还好，刚试了一下最新示例web端，mac mini m2上chrome测试截图，测试最长的200 items，翻页截图花了4秒，合并转换png花了11秒，最终图片是17M，像素1920*26376， 
> 
> 这速度其实等得起，毕竟长截图也不是什么需要大量重复的操作，

我也不确定是什么问题，在iOS上特别慢，可能是像素过大还是什么原因，今天下午能到十分钟。

**Comment by LiWenHui96** [comment]
设置`backgroundColor`后，确实速度会大打折扣，目前没啥问题了。
